# Force explicit Nixpacks configuration for Railway
[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install] 
cmds = [
  "npm ci --only=production",
  "npm ci --only=dev"
]

[phases.build]
cmds = [
  "npm run build",
  "chmod +x start-production.sh",
  "ls -la build/",
  "echo 'Build directory contents:' && ls -la build/"
]

# Final override attempt with explicit script execution
[start]
cmd = "./start-production.sh"