[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm ci && npm run build"

[deploy]
startCommand = "cd frontend && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300

[variables]
NODE_ENV = "production"